# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pubsub.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpubsub.proto\",\n\nPubRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x02 \x01(\t\"\x18\n\x05reply\x12\x0f\n\x07message\x18\x01 \x01(\t\":\n\nSubRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x10\n\x08\x63lientID\x18\x02 \x01(\t\x12\x0b\n\x03TTL\x18\x03 \x01(\x05\x32O\n\x06Pubsub\x12 \n\x07publish\x12\x0b.PubRequest\x1a\x06.reply\"\x00\x12#\n\x08subcribe\x12\x0b.SubRequest\x1a\x06.reply\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pubsub_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PUBREQUEST']._serialized_start=16
  _globals['_PUBREQUEST']._serialized_end=60
  _globals['_REPLY']._serialized_start=62
  _globals['_REPLY']._serialized_end=86
  _globals['_SUBREQUEST']._serialized_start=88
  _globals['_SUBREQUEST']._serialized_end=146
  _globals['_PUBSUB']._serialized_start=148
  _globals['_PUBSUB']._serialized_end=227
# @@protoc_insertion_point(module_scope)
