# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.pubsub_pb2 as pubsub__pb2


class PubsubStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.publish = channel.unary_unary(
                '/Pubsub/publish',
                request_serializer=pubsub__pb2.PubRequest.SerializeToString,
                response_deserializer=pubsub__pb2.reply.FromString,
                )
        self.subcribe = channel.unary_stream(
                '/Pubsub/subcribe',
                request_serializer=pubsub__pb2.SubRequest.SerializeToString,
                response_deserializer=pubsub__pb2.reply.FromString,
                )


class PubsubServicer(object):
    """Missing associated documentation comment in .proto file."""

    def publish(self, request, context):
        """发布消息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def subcribe(self, request, context):
        """订阅消息 使用响应流 可一次处理多个消息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PubsubServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'publish': grpc.unary_unary_rpc_method_handler(
                    servicer.publish,
                    request_deserializer=pubsub__pb2.PubRequest.FromString,
                    response_serializer=pubsub__pb2.reply.SerializeToString,
            ),
            'subcribe': grpc.unary_stream_rpc_method_handler(
                    servicer.subcribe,
                    request_deserializer=pubsub__pb2.SubRequest.FromString,
                    response_serializer=pubsub__pb2.reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Pubsub', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Pubsub(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Pubsub/publish',
            pubsub__pb2.PubRequest.SerializeToString,
            pubsub__pb2.reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def subcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Pubsub/subcribe',
            pubsub__pb2.SubRequest.SerializeToString,
            pubsub__pb2.reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
